apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-database-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-database
  template:
    metadata:
      labels:
        app: accounts-database
    spec:
      containers:
        - name: accounts-database
          image: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-pod
  template:
    metadata:
      labels:
        app: accounts-pod
    spec:
      containers:
        - name: accounts
          image: luccazvps/blog-accounts
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RABBITMQ_URL
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_URL_ACCOUNTS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: accounts-srv
spec:
  type: ClusterIP
  selector:
    app: accounts-pod
  ports:
    - port: 3000
      targetPort: 3000
      name: accounts-port
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-database-srv
spec:
  type: ClusterIP
  selector:
    app: accounts-database
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      name: accounts-port
